name: deploy:api
on:
  workflow_dispatch:
    inputs:
      workflow-run-id:
        description: 'The upstream workflow run id'
        required: true
      artifact-id:
        description: 'The artifact id to deploy'
        required: true
      tag:
        description: 'The tag of the artifact to deploy'
        required: true
        
jobs:     
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        id: download-artifact
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          repository: ${{ vars.DEPLOYMENT_API_REPO }}
          name: ${{ github.event.inputs.artifact-id }}
          run-id: ${{ github.event.inputs.workflow-run-id }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ECR_API_APP_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            deployments/api

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          repository: ${{ vars.ECR_API_APP_URL }}
          tags: ${{ github.event.inputs.tag }}
          push: false     
          context: .
          file: deployments/api/Dockerfile 

  trivy-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ vars.ECR_API_APP_NAME }}:${{ github.event.inputs.tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
  push:
    runs-on: ubuntu-latest
    needs: trivy-check
    steps:
      - name: "Push to ECR"
        run: |
          docker tag ${{ vars.ECR_API_APP_NAME }}:${{ github.event.inputs.tag }} ${{ vars.ECR_API_APP_URL }}:${{ github.event.inputs.tag }}
          docker push ${{ vars.ECR_API_APP_URL }}:${{ github.event.inputs.tag }}
        


